# User

### User 생성하기
POST {{api-url}}/users
Content-Type: application/json

{
  "email": "whitetern@gmail.com",
  "password1": "1234qwer",
  "password2": "1234qwer",
  "name": "홍길동",
  "nickname": "hongd",
  "birthDate": "1990-09-10 11:11:11"
}


### Post
POST {{api-url}}/posts
Content-Type: application/json

{
  "title": "asdsad",
  "content": "sdsd"
}