# User

### User 조회
GET {{api-url}}/users/1


### User 생성
POST {{api-url}}/users
Content-Type: application/json

{
  "loginId": "testid1",
  "password": "!1234qwer",
  "passwordConfirm": "!1234qwer",
  "name": "홍길동",
  "email": "testmail@gmail.com",
  "phone": "010-1234-1234",
  "birthDate": "1990-09-10 11:11:11"
}



